### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by jameshoweee**
Had issues installing tensorflow so proposed a way around this and added to the readme

### CODE REVIEW

**Comment by agohr** [comment]
> 

Thanks for the PR. Could you test if `python -m pip install tensorflow-macos` before installation of the other requirements would resolve the problem for you as well? If so, I would put that into the readme. 

Enabling GPU support via the instructions given at https://developer.apple.com/metal/tensorflow-plugin/ is probably also desirable on eligible devices, but I do not think there is a good way to mention this in the readme without opening up a whole raft of other possible device-specific issues that are not future-proof.

**Comment by jameshoweee** [comment]
Yes that worked :)

**Comment by jameshoweee** [comment]
Following the instructions in https://developer.apple.com/metal/tensorflow-plugin/ worked well for me

**Comment by jameshoweee** [comment]
Changing tensorflow to tensorflow-macos in the requirements.txt also worked!

**Comment by agohr** [comment]
Pull request closed as readme has now been changed in line with the intentions of the PR (albeit not exactly as suggested in the PR).

**Pull request closed without merging**
